//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Atest3.
    /// </summary>
    //  *** Start programmer edit section *** (Atest3 CustomAttributes)

    //  *** End programmer edit section *** (Atest3 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Atest3E", new string[0])]
    [View("Atest3L", new string[0])]
    public class Atest3 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (Atest3 CustomMembers)

        //  *** End programmer edit section *** (Atest3 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Atest3E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Atest3E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Atest3E", typeof(IIS.mu4.Atest3));
                }
            }
            
            /// <summary>
            /// "Atest3L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Atest3L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Atest3L", typeof(IIS.mu4.Atest3));
                }
            }
        }
    }
}
