//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Atesty.
    /// </summary>
    //  *** Start programmer edit section *** (Atesty CustomAttributes)

    //  *** End programmer edit section *** (Atesty CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("AtestyE", new string[0])]
    [View("AtestyL", new string[0])]
    public class Atesty : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (Atesty CustomMembers)

        //  *** End programmer edit section *** (Atesty CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "AtestyE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AtestyE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AtestyE", typeof(IIS.mu4.Atesty));
                }
            }
            
            /// <summary>
            /// "AtestyL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AtestyL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AtestyL", typeof(IIS.mu4.Atesty));
                }
            }
        }
    }
}
